import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Edit Post',
  description: 'Generated by create next app',
}

export default function EditPost() {
  return <h1>Edit Post</h1>
}
