'use client'
import PostSearch from '@/components/PostSearch'
import Posts from '@/components/Posts'
import { getAllPosts } from '@/services/getPosts'
import type { Metadata } from 'next'
import { useEffect, useState } from 'react'

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function Blog() {
  const [posts, setPosts] = useState<any[]>([])
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    getAllPosts()
      .then(setPosts)
      .finally(() => setLoading(false))
  }, [])

  return (
    <>
      <h1>Blog</h1>
      <PostSearch onSearch={setPosts} />
      {loading ? (
        <h3>Loading...</h3>
      ) : (
        <Posts posts={posts} />
      )}
    </>
  )
}
