import PostSearch from '@/components/PostSearch'
import Posts from '@/components/Posts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function Blog() {
  return (
    <>
      <h1>Blog</h1>
      <PostSearch />
      <Posts />
    </>
  )
}
