import type { Metadata } from 'next'
import Link from 'next/link'

async function getData() {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts', {
    next: {
      revalidate: 60,
    },
  })

  if (!response.ok) throw new Error('Error fetching')

  return response.json()
}

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default async function Blog() {
  const posts = await getData()

  return (
    <>
      <h1>Blog</h1>
      {posts.map((post: any) => (
        <li key={post.id}>
          <Link href={`/blog/${post.id}`}>{post.title}</Link>
        </li>
      ))}
    </>
  )
}
