import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About us',
  description: 'Generated by create next app',
}

export default function About() {
  return <h2>Select subitem</h2>
}
