import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Contacts',
  description: 'Generated by create next app',
}

export default function Contacts() {
  return <h2>Contacts</h2>
}
