import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { authConfig } from '../configs/auth'

export const metadata: Metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
}

export default async function Profile() {
  const session = await getServerSession(authConfig)

  return (
    <div>
      <h1>Profile of {session?.user?.name}</h1>
      {session?.user?.image && <img src={session.user.image} alt="" />}
    </div>
  )
}
